title: Site

tabs:
  content:
    label: Pages
    sections:
      pages:
        pages: true

  metadata:
    label: Metadata
    sections:
      content:
        type: fields
        fields:
          author:
            label: Author
            type:  text

          description:
            label: Description
            type:  textarea

          keywords:
            label: Keywords
            type:  tags

          copyright:
            label: Copyright
            type:  textarea